[package]
name = "boost_polygon"
description = "Boost C++ library boost_polygon packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_polygon"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_polygon"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]

[build-dependencies]
zanbil-boost-build = "0.1.0"
